version: '3'

services:
  big-backend:
    image: opendatav:v1.0
    container_name: opendatav
    restart: always
    ports:
      - '7654:7654'
    environment:
      - 'TZ=Asia/Shanghai'
      - 'INSTANCE=1'
      - 'DB_HOST=10.10.8.252'
      - 'DB_PORT=3306'
      - 'DB_NAME=backend'
      - 'DB_PASSWD=123456'
